- name: Fetch latest VirtualBox version
  ansible.builtin.uri:
    url: "https://download.virtualbox.org/virtualbox/LATEST.TXT"
    return_content: true
  register: virtualbox_version_response

- name: Set VirtualBox version
  ansible.builtin.set_fact:
    virtualbox_version: "{{ virtualbox_version_response.content | trim }}"

- block:
    - name: Install pexpect in order to accept virtualboxes EULA
      ansible.builtin.package:
        name: virtualbox
        state: present

    - name: Install VirtualBox
      ansible.builtin.package:
        name: python-pexpect
        state: present

    - name: Download VirtualBox Extension Pack
      ansible.builtin.get_url:
        url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
        dest: "/tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
        mode: '0777'

    - name: Accept EULA for VirtualBox Extension Pack
      ansible.builtin.expect:
        command: >
          VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack
        responses:
          Do you agree? [y/n]: "y"
          Do you agree to these license terms and conditions (y/n)?: "y" 
      args:
        creates: "/usr/lib/virtualbox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack"

    - name: Clean up Extension Pack file
      ansible.builtin.file:
        path: "/tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
        state: absent
  when: virtualbox_version is defined
  name: "Install VirtualBox and Extension Pack"
