---
# Common pre-tasks for all hosts
- name: Pre-configuration tasks
  hosts: all
  become: true
  tags:
    - always
    - setup

  pre_tasks:
    - name: Update package cache (Arch Linux)
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Archlinux"
      tags:
        - always

  tasks:
    - name: Install required system packages
      ansible.builtin.package:
        name: "{{ required_packages }}"
        state: present
      vars:
        required_packages:
          - unrar
          - rsync
      tags:
        - packages
        - setup

# Role-based configurations
- name: Apply base configuration
  hosts: all
  become: true
  roles:
    - base

- name: Configure workstation
  hosts: workstation
  become: true
  roles:
    - workstation

#  - name: set up sudo for ansible user
#    copy:
#      src: files/sudoer_vgscq
#      dest: /etc/sudoers.d/vgscq
#      owner: root
#      group: root
#      mode: 0440

#  - name: create ansible-pull service file
#    copy:
#      dest: /etc/systemd/system/ansible-pull.service
#      content: |
#        [Unit]
#        Description=Run ansible-pull for auto-provisioning
#
#        [Service]
#        User=vgscq
#        ExecStart=/usr/bin/ansible-pull -o -U https://github.com/vggscqq/ansible-system-config.git
#        WorkingDirectory=/home/vgscq
#        Environment=HOME=/home/vgscq
#        Environment=USER=vgscq
#
#  - name: create ansible-pull timer file
#    copy:
#      dest: /etc/systemd/system/ansible-pull.timer
#      content: |
#        [Unit]
#        Description=Run ansible-pull every 30 minutes
#
#        [Timer]
#        OnCalendar=*:0/30
#        Persistent=true
#
#        [Install]
#        WantedBy=timers.target
#
#  - name: reload systemd
#    command: systemctl daemon-reload
#
#  - name: enable and start ansible-pull timer
#    systemd:
#      name: ansible-pull.timer
#      enabled: yes
#      state: started