- name: Gnome | appearance | Pinned apps bar
  hosts: all
  become: true
  become_user: vgscq
  vars:
    required_apps:
      - 'firefox.desktop'
      - 'org.telegram.desktop.desktop'
      - 'spotify.desktop'
  tasks:
    - name: Get the current list of pinned apps
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        state: read
      register: current_pinned_apps

    - name: Ensure the current pinned apps list is not None
      ansible.builtin.set_fact:
        pinned_apps: "{{ current_pinned_apps.value | default([]) }}"

    - name: Determine remaining apps
      ansible.builtin.set_fact:
        remaining_apps: "{{ pinned_apps | difference(required_apps) }}"

    - name: Ensure Firefox, Telegram, and Spotify are the first in the list
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "{{ required_apps + remaining_apps }}"
