# Load distro-specific variables
- name: Load distro-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Ensure necessary workstation tasks are imported
  block:

    - name: Install gnome
      ansible.builtin.import_tasks: desktop_environments/gnome/packages.yml

    - name: Install gnome extra
      ansible.builtin.import_tasks: desktop_environments/gnome/extra_packages.yml

    - name: Gnome | config | peripherals
      ansible.builtin.import_tasks: desktop_environments/gnome/peripherals.yml

    - name: Gnome | config | shell settings
      ansible.builtin.import_tasks: desktop_environments/gnome/shell_settings.yml

    - name: Gnome | config | Terminal
      ansible.builtin.import_tasks: desktop_environments/gnome/terminal.yml

    - name: Gnome | config | Appearance
      ansible.builtin.import_tasks: desktop_environments/gnome/appearance.yml

    - name: System tweaks
      ansible.builtin.import_tasks: system_setup/tweaks.yml

    - name: Gnome | Keybinds
      ansible.builtin.import_tasks: desktop_environments/gnome/keybindings.yml

    - name: Extra software | VirtualBox
      ansible.builtin.import_tasks: extra_software/virtualbox.yml

    - name: Extra software | Telegram
      ansible.builtin.import_tasks: extra_software/telegram.yml
