# distro-specific tasks for ubuntu
- name: System setup | tweaks | disable apport in config on ubuntu-based hosts
  tags: distro,distro-setup,apport,ubuntu
  ansible.builtin.lineinfile:
    dest: /etc/default/apport
    regexp: "enabled="
    line: "enabled=0"
  when: ansible_distribution in ["Ubuntu"]

- name: System setup | tweaks | disable and stop apport service on ubuntu-based hosts
  tags: distro,distro-setup,apport,ubuntu
  ansible.builtin.service:
    name: apport
    enabled: false
    state: stopped
  when: ansible_distribution in ["Ubuntu"]

- name: Setup udev
  become: true
  ansible.builtin.copy:
    src: udev/{{ item.src }}
    dest: /etc/udev/rules.d/{{ item.dest }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: '99-dockstations.rules', dest: '99-dockstations.rules' }
    - { src: '99-low-battery.rules', dest: '99-low-battery.rules' }

- name: Copy udev handlers
  become: true
  ansible.builtin.copy:
    src: udev/{{ item.src }}
    dest: /home/vgscq/.config/bin/{{ item.dest }}
    owner: vgscq
    group: vgscq
    mode: '0755'
  with_items:
    - { src: 'battery.sh', dest: 'battery.sh' }
    - { src: 'battery_off.sh', dest: 'battery_off.sh' }

- name: Gnome | Extensions | Executor copy powermon.sh
  tags: gnome,gnome-wallpaper
  ansible.builtin.copy:
    src: gnome/powermon.sh
    dest: /home/vgscq/.config/bin/
    owner: vgscq
    group: vgscq
    mode: '0755'
