- name: Gnome | appearance | set dark theme
  tags: gnome,gnome-wallpaper
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Gnome | appearance | Create wallpaper directory
  ansible.builtin.file:
    path: "/usr/share/backgrounds/vgscq/"
    state: directory
    mode: '0755'
  become: true

- name: Gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  ansible.builtin.copy:
    src: gnome/green.jpg
    dest: /usr/share/backgrounds/vgscq/vgscq-wallpaper.png
    owner: root
    group: root
    mode: '0644'

- name: Gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/vgscq/vgscq-wallpaper.png'"

- name: Gnome | Set picture options to 'zoom' for background and screensaver
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "{{ item }}"
    value: "'zoom'"
  with_items:
    - "/org/gnome/desktop/background/picture-options"
    - "/org/gnome/desktop/screensaver/picture-options"

- name: Gnome | Remove camera shutter sound file
  tags: gnome,gnome-shell
  become: true
  ansible.builtin.file:
    path: /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
    state: absent

- name: Gnome | Calendar show week date
  tags: gnome,shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"

- name: Gnome | appearance | Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Gnome | appearance | Create fonts directory
  ansible.builtin.file:
    path: "/usr/share/fonts/sf-mono"
    state: directory
    mode: '0755'
  become: true

- name: Gnome | appearance | Unzip sf-mono-fonts.zip
  ansible.builtin.unarchive:
    src: gnome/sfmono.zip
    dest: "/usr/share/fonts/sf-mono"
  become: true

- name: Gnome | appearance | Refresh font cache
  ansible.builtin.command: fc-cache -f -v
  changed_when: true
  become: true

- name: Gnome | appearance | Configure favorite apps in dock
  block:
    - name: Read current favorite apps configuration
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        state: read
      register: current_pinned_apps

    - name: Set default pinned apps list if none exists
      ansible.builtin.set_fact:
        current_favorites: "{{ current_pinned_apps.value | default([]) }}"

    - name: Update favorite apps configuration
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "{{ favorite_apps_order + (current_favorites | difference(favorite_apps_order)) }}"

  become: true
  become_user: vgscq
  vars:
    favorite_apps_order:
      - 'firefox.desktop'
      - 'org.telegram.desktop.desktop'
      - 'spotify.desktop'

- name: Gnome | appearance | Download profile picture
  become: true
  get_url:
    url: https://i.imgur.com/mqsRlbt.png
    dest: /var/lib/AccountsService/icons/vgscq
    force: true

- name: Gnome | appearance | Set profile picture
  become: true
  lineinfile:
    path: /var/lib/AccountsService/users/vgscq
    regexp: '^Icon='
    line: 'Icon=/var/lib/AccountsService/icons/vgscq'



- name: Gnome | Extensions | Executor install
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/extensions/executor/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: center-active, value: "false" }
    - { key: left-active, value: "false" }
    - { key: right-active, value: "true" }
    - key: right-commands-json
      value: >
        '{"commands":[{"isActive":true,"command":"/home/vgscq/.config/bin/powermon.sh",\
        "interval":5,"uuid":"d64681a8-4e6b-4f3f-85f3-d0c56580ba14"}]}'

- name: Gnome | Extensions | Dash to Dock settings
  tags: gnome,dash-to-dock
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: always-center-icons, value: "true" }
    - { key: apply-custom-theme, value: "false" }
    - { key: background-opacity, value: "0.80000000000000004" }
    - { key: custom-theme-shrink, value: "true" }
    - { key: dash-max-icon-size, value: "24" }
    - { key: dock-fixed, value: "false" }
    - { key: dock-position, value: "'BOTTOM'" }
    - { key: extend-height, value: "false" }
    - { key: height-fraction, value: "0.90000000000000002" }
    - { key: intellihide-mode, value: "'FOCUS_APPLICATION_WINDOWS'" }
    - { key: max-alpha, value: "0.80000000000000004" }
    - { key: multi-monitor, value: "true" }
    - { key: require-pressure-to-show, value: "false" }
    - { key: transparency-mode, value: "'DYNAMIC'" }

- name: Gnome | Shell | Disable extension version validation
  tags: gnome,shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/disable-extension-version-validation"
    value: "true"

- name: Gnome | Shell | Set CZ date format
  tags: gnome,shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/system/locale/region"
    value: "'cs_CZ.UTF-8'"

- name: Gnome | Shell | 12h format
  tags: gnome,shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

- name: Gnome | Window Manager | Set button layout
  tags: gnome,wm
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,close'"

- name: Ensure the lines are uncommented in /etc/locale.gen
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^#(cs_CZ.UTF-8 UTF-8|en_US.UTF-8 UTF-8)"
    line: "\\1"
    state: present
    backrefs: yes
  register: locale_gen_changed

- name: Gnome | Locale | Generate locales using locale-gen
  ansible.builtin.command: locale-gen
  when: locale_gen_changed.changed

