- name: Gnome | appearance | set dark theme
  tags: gnome,gnome-wallpaper
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Gnome | appearance | Create wallpaper directory
  ansible.builtin.file:
    path: "/usr/share/backgrounds/vgscq/"
    state: directory
    mode: '0755'
  become: true

- name: Gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  ansible.builtin.copy:
    src: gnome/3.jpg
    dest: /usr/share/backgrounds/vgscq/vgscq-wallpaper.png
    owner: root
    group: root
    mode: '0644'

- name: Gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/vgscq/vgscq-wallpaper.png'"

- name: Gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'stretched'"

- name: Gnome | appearance | Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Gnome | appearance | Create fonts directory
  ansible.builtin.file:
    path: "/usr/share/fonts/sf-mono"
    state: directory
    mode: '0755'
  become: true

- name: Gnome | appearance | Unzip sf-mono-fonts.zip
  ansible.builtin.unarchive:
    src: gnome/sfmono.zip
    dest: "/usr/share/fonts/sf-mono"
  become: true

- name: Gnome | appearance | Refresh font cache
  ansible.builtin.command: fc-cache -f -v
  changed_when: true
  become: true

- name: Gnome | appearance | Pinned apps bar
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.mozilla.firefox.desktop', \
      'org.telegram.desktop.desktop', \
      'com.spotify.Client.desktop', \
      'org.gnome.Terminal.desktop', \
      'org.gnome.Nautilus.desktop', \
      'winbox.desktop', \
      'code.desktop', \
      'virtualbox.desktop', \
      'org.gnome.TextEditor.desktop', \
      'org.remmina.Remmina.desktop', \
      'io.github.brunofin.Cohesion.desktop']"

- name: Gnome | Extensions | Executor install
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/extensions/executor/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: center-active, value: "false" }
    - { key: left-active, value: "false" }
    - { key: right-active, value: "true" }
    - key: right-commands-json
      value: >
        '{"commands":[{"isActive":true,"command":"/home/vgscq/.config/bin/powermon.sh","interval":5,"uuid":"d64681a8-4e6b-4f3f-85f3-d0c56580ba14"}]}'
