- name: Gnome | packages | extra packages
  tags: gnome,gnome-packages
  ansible.builtin.package:
    name:
      - "{{ telegram_package }}"
      - firefox
      - "{{ spotify_package }}"
      - "remmina"
      - "{{ virtualbox_package }}"
      - "{{ gstreamer_libav_package }}"
      - "{{ gstreamer_plugins_bad_package }}"

# - name: Gnome | YAY | Install cohesion [1/2]
#   become_user: vgscq
#   become: true
#   ansible.builtin.command:
#     cmd: yay -S --noconfirm nvm
#   args:
#     creates: /usr/share/nvm/nvm.sh
#   when: ansible_distribution == "Archlinux"

# - name: Gnome | YAY | Install cohesion [2/2]
#   become_user: vgscq
#   become: true
#   ansible.builtin.command:
#     cmd: yay -S --noconfirm cohesion-git
#   args:
#     creates: /usr/bin/cohesion
#   when: ansible_distribution == "Archlinux"
