- name: Gnome | packages | extra packages
  tags: gnome,gnome-packages
  ansible.builtin.package:
    name:
      - "{{ telegram_package }}"
      - firefox
      - "{{ spotify_package }}"
      - "remmina"
      # - "{{ virtualbox_package }}"
      - "{{ gstreamer_libav_package }}"
      - "{{ gstreamer_plugins_bad_package }}"
      - qbittorrent
      - vlc
      - xorg-xwayland

- name: Gnome | YAY | Install nvm
  yay:
    name:
      - nvm
    state: latest

- name: Gnome | YAY | Install notion
  yay:
    name:
      - notion-app-electron
    state: latest

- name: Gnome | YAY | Install spotify
  yay:
    name:
      - spotify
    state: latest

- name: Gnome | YAY | Install vs code
  yay:
    name:
      - visual-studio-code-bin
    state: latest

- name: Qbittorrent config copy
  ansible.builtin.copy:
    src: config/qBittorrent
    dest: /home/vgscq/.config/
    owner: vgscq
    group: vgscq
    mode: '0644'
