- name: Gnome | keybindings | Terminal
  tags: gnome,keybindings
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Terminal'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Control><Alt>t'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'gnome-terminal'" }

- name: Gnome | keybindings | Nautilus
  tags: gnome,keybindings
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'Explorer.exe'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Super>e'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'nautilus'" }


- name: Gnome | shell settings | Apply custom bindings
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

- name: Gnome | keybindings | Screenshot
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/screenshot"
    value: "['Print']"

- name: Gnome | keybindings | Screenshot window
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/screenshot-window"
    value: "['<Alt>Print']"

- name: Gnome | keybindings | Screenshot area
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/show-screenshot-ui"
    value: "['<Shift>Print']"

- name: Gnome | keybindings | Screen recording (disable)
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/show-screen-recording-ui"
    value: "['']"

- name: Gnome | Keybindings | Switch workspace only
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/shell/window-switcher/current-workspace-only"
    value: "false"

- name: Gnome | Keybindings | Switch windows
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
