- name: Gnome | packages | install gnome packages
  tags: gnome,gnome-packages
  ansible.builtin.package:
    name:
      - eog
      - file-roller
      - "{{ gdm_package }}"
      - gedit
      - gnome-backgrounds
#      - gnome-books
#      - gnome-boxes
      - gnome-control-center
      - gnome-disk-utility
#      - gnome-documents
#      - gnome-icon-theme
#      - gnome-music
#      - gnome-photos
      - gnome-power-manager
      - gnome-remote-desktop
      - gnome-shell
      - gnome-shell-extensions
#      - gnome-system-monitor
#      - gnome-terminal
 #     - gnome-todo
      - gnome-tweaks
      - nautilus
      - "{{ power_profiles_package }}"
      - dconf-editor

# It appears as though Debian and Ubuntu place GNOME support for openvpn in a separate package
# This doesn't seem to be required in archlinux.
- name: Gnome | packages | install gnome support for network-manager for debian and ubuntu hosts
  tags: gnome,gnome-packages,packages
  ansible.builtin.package:
    name:
      - network-manager-openvpn-gnome
  when: ansible_distribution in ["Ubuntu"]

- name: Remove gnome-terminal
  community.general.pacman:
    name: gnome-terminal
    state: absent
  when: ansible_distribution == "Archlinux"

- name: Install gnome-terminal-transparency using yay
  ansible.builtin.command:
    cmd: yay -S --noconfirm gnome-terminal-transparency
  args:
    creates: /usr/bin/gnome-terminal-transparency
  when: ansible_distribution == "Archlinux"

- name: Install gnome-extensions-cli using yay
  ansible.builtin.command:
    cmd: yay -S --noconfirm gnome-extensions-cli
  args:
    creates: /usr/bin/gnome-extensions-cli
  when: ansible_distribution == "Archlinux"

- name: Install gnome connector
  ansible.builtin.package:
    name:
      - gnome-browser-connector
  when: ansible_distribution == "Archlinux"


- name: Gnome | packages | enable and start gdm
  tags: autofs,system,system setup
  ansible.builtin.service:
    name: gdm
    enabled: true
    state: started
