- name: Gnome | shell settings | button-layout
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,close'"

# - name: Gnome | shell settings | event-sounds (disable)
#   tags: gnome,audio,sounds,alerts
#   become_user: vgscq
#   become: true
#   community.general.dconf:
#     key: "/org/gnome/desktop/sound/event-sounds"
#     value: "false"

# Disable screen blanking
- name: Gnome | shell settings | idle-delay
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 0"

- name: Gnome | shell settings | Allow volume above 100 percent
  tags: gnome,audio,sounds,alerts
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "true"

- name: Gnome | shell settings | old-files-age
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/old-files-age"
    value: "uint32 14"

- name: Gnome | shell settings | remove-old-temp-files
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/remove-old-temp-files"
    value: "true"

- name: Gnome | shell settings | remove-old-trash-files
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/privacy/remove-old-trash-files"
    value: "true"

- name: Gnome | shell settings | search-providers
  tags: gnome,search,skip_ansible_lint
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/search-providers/disabled"
    value: "['org.gnome.Nautilus.desktop', \
      'org.gnome.Calculator.desktop', \
      'org.gnome.seahorse.Application.desktop', \
      'org.gnome.Photos.desktop', \
      'org.gnome.Terminal.desktop', \
      'org.gnome.Documents.desktop', \
      'org.gnome.Contacts.desktop', \
      'org.gnome.Calendar.desktop']"

- name: Gnome | shell settings | show-battery-percentage
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Gnome | shell settings | workspaces-only-on-primary
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "true"

- name: Gnome | shell settings | set gnome-screenshot default save directory
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/gnome-screenshot/auto-save-directory"
    value: "'/tmp'"

- name: Gnome | shell settings | Make SF Mono a monospace font
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'SF Mono Medium 10'"

- name: Gnome | Mutter | Enable experimental features for scaling
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/mutter/experimental-features"
    value: "['scale-monitor-framebuffer']"

- name: Gnome | nautilus | set directories to be shown first
  tags: gnome,gnome-shell
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gtk/settings/file-chooser/sort-directories-first"
    value: "true"

- name: Gnome | shell | Disable suspend by timeout
  tags: gnome,terminal
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: sleep-inactive-battery-type, value: "'nothing'" }
    - { key: sleep-inactive-ac-type, value: "'nothing'" }


- name: Gnome | Fish greeting | Enable workstation mode | fish_greeting.fish
  ansible.builtin.lineinfile:
    path: /home/vgscq/.config/fish/functions/fish_greeting.fish
    regexp: '^(\s*python\s+~/.config/fish/greeting.py\s*)$'
    line: '    python ~/.config/fish/greeting.py workstation'
    state: present

- name: Copy TODOs
  ansible.builtin.copy:
    src: TODO
    dest: /home/vgscq/
    owner: vgscq
    group: vgscq
    mode: '0644'

- name: Find all .sh files in the TODO directory
  ansible.builtin.find:
    paths: /home/vgscq/TODO
    patterns: '*.sh'
  register: sh_files

- name: Make .sh files executable
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ sh_files.files }}"
  when: sh_files.matched > 0
