- name: Gnome | terminal | make F10 work
  tags: gnome,gnome-shell,terminal
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/menu-accelerator-enabled"
    value: "false"

- name: Gnome | terminal | set terminal configuration
  tags: gnome,terminal
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: background-transparency-percent, value: "10" }
    - { key: default-size-columns, value: "116" }
    - { key: default-size-rows, value: "30" }
    - { key: font, value: "'SF Mono 12'" }
    - { key: use-system-font, value: "false"}
    - { key: use-transparent-background, value: "true"}

- name: Gnome | terminal | set terminal keybindings
  tags: gnome,terminal
  become_user: vgscq
  become: true
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: new-tab, value: "'<Primary>t'" }
    - { key: next-tab, value: "'<Primary>Right'"}
    - { key: prev-tab, value: "'<Primary>Left'"}
