- name: System setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - fish
      - curl
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - rsync
      - sshfs
      - tmux
      - traceroute
      - "{{ nvim_package }}"
      - wget
      - "{{ python_pip_package }}"
      - "{{ python_passlib_package }}"
      - "{{ python_psutil_package }}"
      - tailscale
      - jq
      - less
      - dnsmasq
      - bc
      - wireguard-tools
