- name: System setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - fish
      - curl
      - htop
      - lm_sensors
      - lsof
      - mc
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - rsync
      - sshfs
      - tmux
      - traceroute
      - neovim
      - wget
      - python-pip
      - python-passlib
      - python-psutil
      - tailscale
      - jq
      - less
      - dnsmasq
      - bc
      - wireguard-tools
