# install yay on archlinux
- name: Clone yay
  tags: skip_ansible_lint
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/tmp/yay"
    update: true
  when: ansible_distribution == "Archlinux"

- name: Change ownership of /tmp/yay to vgscq
  ansible.builtin.file:
    path: /tmp/yay
    owner: vgscq
    group: vgscq
    state: directory
  become: yes

- name: Build and install yay
  ansible.builtin.command:
    chdir: "/tmp/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  when: ansible_distribution == "Archlinux"
  become: yes
  become_user: vgscq

