# install yay on archlinux
- name: Ensure /tmp/yay is absent
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
  become: true

- name: Clone yay
  tags: skip_ansible_lint
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/tmp/yay"
    update: true

- name: Change ownership of /tmp/yay to vgscq
  ansible.builtin.file:
    path: /tmp/yay
    owner: vgscq
    group: vgscq
    mode: '0755'
    state: directory
  become: true

- name: Build and install yay
  ansible.builtin.command:
    chdir: "/tmp/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  become: true
  become_user: vgscq

- name: Ensure /tmp/yay is absent
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
  become: true
