- name: Ensure necessary basic tasks are imported
  block:
    # Install software
    - name: Import software installation tasks
      ansible.builtin.import_tasks: software/basic.yml

    # Make sure user exist on the system
    - name: Import user tasks
      ansible.builtin.import_tasks: users/vgscq.yml

    # Make sure yay installed
    - name: Install yay
      ansible.builtin.import_tasks: software/yay.yml

    - name: Import networking tasts
      ansible.builtin.import_tasks: networking.yml
      ansible.builtin.import_tasts: networking_handlers.yml
