# Load distro-specific variables
- name: Load distro-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Ensure necessary tasks are imported
  block:
    # Install software
    - name: Import software installation tasks
      ansible.builtin.import_tasks: software/basic.yml

    # Make sure user exist on the system
    - name: Import user tasks
      ansible.builtin.import_tasks: users/vgscq.yml

    # Make sure yay installed
    - name: Install yay
      ansible.builtin.import_tasks: software/yay.yml
      when: ansible_distribution == "Archlinux"
