- block:
  # Make sure user exist on the system
  - import_tasks: users/vgscq.yml


  # install software
  - import_tasks: software/basic.yml

  # Perform remaining tasks:
#  - import_tasks: system_setup/clock.yml
#  - import_tasks: system_setup/cron.yml
#  - import_tasks: system_setup/locale.yml
#  - import_tasks: system_setup/logging.yml
#  - import_tasks: system_setup/memory.yml
#  - import_tasks: system_setup/microcode.yml
#  - import_tasks: system_setup/openssh.yml
#  - import_tasks: system_setup/scripts.yml