- name: Networking | Ensure tailscaled service is enabled and running
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started

- name: Networking | Configure dnsmasq
  become: true
  ansible.builtin.copy:
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      # DNS --------------------------------------------------------------------------

      user=dnsmasq
      group=dnsmasq
      interface=lo
      #bind-interfaces
      cache-size=1000

      # Never forward plain names (without a dot or domain part)
      domain-needed
      # Never forward addresses in the non-routed address spaces.
      bogus-priv

      # If you don't want dnsmasq to read /etc/resolv.conf
      no-resolv
      no-poll
      localise-queries

      # roboauto
      server=/roboauto.lan/10.139.0.1
      server=/roboauto.tech/10.139.0.1
      server=/int.roboauto.tech/10.139.0.1

      # my
      server=/ts.net/100.100.100.100

      # default
      server=1.1.1.1

- name: Networking | Ensure NetworkManager is configured with dns=none in [main] section
  become: true
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none
    mode: '0644'
    backup: true
  register: networkmanager_config

- name: Networking | Ensure /etc/resolv.conf is not a symlink
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: file
    force: true

- name: Networking | Ensure /etc/resolv.conf points to local dns server
  become: true
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      nameserver 127.0.0.1

- name: Networking | Ensure dnsmasq service is enabled and running
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true
    state: restarted